name: Docker Image CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t webapp-color-frontend:$(date +%s) .
    - name: Show Docker Images  
      run: docker images